name: wad2gltf-gh-actions
run-name: wad2gltf runner
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - name: check g version
        run: g++ --version
      - name: check gcc version
        run: gcc --version
      - name: build application with cmake
        run: cmake .
      - name: make build
        run: make
